# Generated by Django 5.2.12 on 2026-05-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('mineral_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('image', models.ImageField(upload_to='recognitions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
