# Generated by Django 5.2.12 on 2026-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('mineral_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('user_id', 'mineral_name')},
            },
        ),
    ]
