# Generated by Django 6.0.2 on 2026-02-23 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата распознавания')),
                ('source', models.CharField(choices=[('upload', 'Загрузка'), ('camera', 'Камера')], default='upload', max_length=10, verbose_name='Источник')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recognitions/', verbose_name='Фото')),
                ('top1_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Top-1 минерал')),
                ('top1_conf', models.FloatField(blank=True, null=True, verbose_name='Top-1 вероятность')),
                ('top2_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Top-2 минерал')),
                ('top2_conf', models.FloatField(blank=True, null=True, verbose_name='Top-2 вероятность')),
                ('top3_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Top-3 минерал')),
                ('top3_conf', models.FloatField(blank=True, null=True, verbose_name='Top-3 вероятность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История распознавания',
                'verbose_name_plural': 'История распознаваний',
                'ordering': ['-created_at'],
            },
        ),
    ]
