# Generated by Django 6.0.2 on 2026-03-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionhistory',
            name='predicted_mineral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognitions', to='catalog.mineral', verbose_name='Распознанный минерал'),
        ),
    ]
