# Generated by Django 6.0.2 on 2026-03-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Ключ модели')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('formula', models.CharField(blank=True, max_length=200, verbose_name='Формула')),
                ('color', models.CharField(blank=True, max_length=200, verbose_name='Цвет')),
                ('hardness', models.CharField(blank=True, max_length=100, verbose_name='Твёрдость')),
                ('origin', models.TextField(blank=True, verbose_name='Происхождение')),
                ('usage', models.TextField(blank=True, verbose_name='Применение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('facts', models.JSONField(blank=True, default=list, verbose_name='Интересные факты')),
                ('category', models.CharField(choices=[('mineral', 'Минерал'), ('rock', 'Горная порода'), ('glass', 'Вулканическое стекло'), ('gem', 'Драгоценный камень')], default='mineral', max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='minerals/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Минерал',
                'verbose_name_plural': 'Минералы',
                'ordering': ['title'],
            },
        ),
    ]
