# Generated by Django 5.2.12 on 2026-03-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_slug', models.SlugField(max_length=150, verbose_name='ML класс (raw slug)')),
                ('canonical_key', models.SlugField(max_length=150, verbose_name='Негізгі ғылыми кілт')),
                ('lang', models.CharField(choices=[('kk', 'Қазақша'), ('ru', 'Русский'), ('en', 'English')], max_length=2, verbose_name='Тіл')),
                ('title', models.CharField(max_length=255, verbose_name='Атауы')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='Түсі / Цвет / Colour')),
                ('formula', models.CharField(blank=True, max_length=255, verbose_name='Формула')),
                ('luster', models.CharField(blank=True, max_length=255, verbose_name='Жылтырлығы / Блеск / Luster')),
                ('mohs_scale', models.CharField(blank=True, max_length=100, verbose_name='Қаттылығы / Mohs scale')),
                ('cleavage', models.CharField(blank=True, max_length=255, verbose_name='Жіктілігі / Спайность / Cleavage')),
                ('fracture', models.CharField(blank=True, max_length=255, verbose_name='Сынықтылығы / Излом / Fracture')),
                ('crystal_system', models.CharField(blank=True, max_length=255, verbose_name='Сингониясы / Crystal system')),
                ('description', models.TextField(blank=True, verbose_name='Түсіндірмесі / Описание / Description')),
                ('origin', models.TextField(blank=True, verbose_name='Шығу тегі / Происхождение / Origin')),
                ('uses', models.TextField(blank=True, verbose_name='Пайдалануы / Применение / Uses')),
                ('deposits', models.TextField(blank=True, verbose_name='Кенорындары / Месторождения / Deposits')),
                ('interesting_facts', models.JSONField(blank=True, default=list, verbose_name='Қызықты факттер')),
                ('image', models.ImageField(blank=True, null=True, upload_to='minerals_i18n/')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Тексерілген бе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Көптілді минерал',
                'verbose_name_plural': 'Көптілді минералдар',
                'ordering': ['lang', 'title'],
                'unique_together': {('raw_slug', 'lang')},
            },
        ),
    ]
